### ISSUE TITLE
Extending the letter set

### ISSUE THREAD

**Issue by ghost** [dukn/Captcha-recognition-Keras#1]
Hello @dukn. Is it possible to extend the letter set to contain small and capital letters and numbers?
I tried modifying the Captcha generation scripts and `utils.py` and generated the data but it fails at training. If possible please tell me how to extend it so it will contain the entire alphabet set.

The Error Message:

`python Train.py
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from float to np.floating is deprecated. In future, it will be treated as np.float64 == np.dtype(float).type. from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "Train.py", line 26, in <module>
    x_train = np.asarray(x_train)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/numeric.py", line 492, in asarray
    return array(a, dtype, copy=False, order=order)
MemoryError
Makefile:14: recipe for target 'train' failed
make: *** [train] Error 1
`

**Comment by dukn** [comment]
Your ram is not enough to run it

**Comment by thehoangtrong** [comment]
Hello Dukn,
I don't have linux for testing your application. Could you please check that your application can resolve below captcha:
https://drive.google.com/file/d/1D12iollW0Y3fv730S3WSFjGaNI3BC93p/view?usp=sharing

Thank you very much in advanced.

**Comment by dukn** [comment]
@thehoangtrong The model can recognize this type of captcha, but the accuracy isn't high. To increase, you need to re-train the model with dataset like this sample.

**Comment by thehoangtrong** [comment]
Could you please guide me how to prepare training data?

Thank you very much for quick answer!

**Comment by dukn** [comment]
@thehoangtrong  First, you must prepare a captcha generator (like Captcha_Generator/Captcha-php) to create data for training phase. Have you got it?
