### ISSUE TITLE
make captcha

### ISSUE THREAD

**Issue by rok356** [dukn/Captcha-recognition-Keras#2]
Hello @dukn I have some problems with running the project. It fails at "make captcha" command. Error message is listed below. I think there is problem in "Captcha_Generator/Captcha-php/demo/Data/", there is no "Data" directory in "demo" folder on repository. How can I make it work? Thanks.

Error:
php Captcha_Generator/Captcha-php/demo/demo.php
PHP Warning:  fopen(Data/pass.txt): failed to open stream: No such file or directory in /home/rok/Captcha-recognition-Keras/Captcha_Generator/Captcha-php/demo/demo.php on line 10
PHP Fatal error:  Uncaught Error: Call to undefined function Gregwar\Captcha\imagecreatetruecolor() in /home/rok/Captcha-recognition-Keras/Captcha_Generator/Captcha-php/CaptchaBuilder.php:403
Stack trace:
#0 /home/rok/Captcha-recognition-Keras/Captcha_Generator/Captcha-php/demo/demo.php(14): Gregwar\Captcha\CaptchaBuilder->build()
#1 {main}
  thrown in /home/rok/Captcha-recognition-Keras/Captcha_Generator/Captcha-php/CaptchaBuilder.php on line 403
make: *** [Makefile:8: captcha] Error 255

**Comment by dukn** [comment]
@rok356 , 
Yes, 
We need an empty directory "./Data". 
I edited Makefile to create it.
Now, you can pull and try to create captcha.
Thanks for report :+1:
